README.md
package.json

> ~~good svelte ui~~
bikeshedding/brainstorming welcome
edit:
going with Ham's suggestion:
> svelte ui that feels good

add tagline

---

README.md
package.json

Capitalizes the tagline per our conversation:
~~svelte ui that feels good~~
Svelte UI that feels good

capitalize the tagline

---

README.md
package-lock.json
package.json

This renames the project from `felt-ui` to `felt`.

rename to felt

---

package-lock.json
package.json

This updates the lockfile to v2:
```
rm -rf node_modules package-lock.json
npm i
```

update lockfile to v2

---

src/routes/index.svelte

This adds a greeting for anyone who might stumble upon felt.dev, making it less confusing, hopefully.

add a header message

---

README.md
package.json
src/routes/index.svelte

This updates the main page and updates the tagline to `web tech that feels good`. It's currently deployed to felt.dev via `gro deploy --branch update-links`

update links and tagline

---

package-lock.json
package.json
src/gro.config.ts

This upgrades Gro and removes a line of config that is no longer necessary.

upgrade gro and remove unncessary config line

---

README.md
src/app.css
src/consent/Consent_Principle_View.svelte
src/consent/consent.ts
src/lib/Checkbox.svelte
src/lib/Content.svelte
src/lib/Message.svelte
src/lib/Nav.svelte
src/onboard/Credits.svelte
src/onboard/Nav.svelte
src/onboard/Onboard.svelte
src/onboard/Onboard_State.svelte
src/onboard/consentful/Begin.svelte
src/onboard/consentful/End.svelte
src/onboard/consentful/Informed.svelte
src/onboard/consentful/Revertible.svelte
src/onboard/unconsentful/End.svelte
src/onboard/unconsentful/Informed.svelte
src/onboard/unconsentful/Revertible.svelte
src/onboard/unconsentful/Unburdensome.svelte
src/onboard/unconsentful/Voluntary.svelte
src/routes/__layout.svelte
src/routes/index.svelte
src/xstate/Machine_Controls.svelte

onboard study

---

README.md
src/app.css
src/lib/Checkbox.svelte
src/lib/Message.svelte
src/onboard/Onboard.svelte
src/onboard/consentful/Informed.svelte
src/onboard/consentful/Revertible.svelte
src/onboard/unconsentful/Informed.svelte
src/onboard/unconsentful/Revertible.svelte
src/onboard/unconsentful/Unburdensome.svelte
src/onboard/unconsentful/Voluntary.svelte

Let's merge this whenever you review it. Could be now, or tomorrow, whatever works. I'll keep adding and deploying commits in the meantime.

design system and other details

---

src/onboard/consentful/Begin.svelte
src/onboard/consentful/End.svelte
src/onboard/consentful/Informed.svelte
src/onboard/consentful/Specific.svelte
src/onboard/consentful/Unburdensome.svelte
src/onboard/consentful/Voluntary.svelte
src/onboard/unconsentful/Begin.svelte
src/onboard/unconsentful/End.svelte
src/onboard/unconsentful/Informed.svelte
src/onboard/unconsentful/Revertible.svelte
src/onboard/unconsentful/Specific.svelte
src/onboard/unconsentful/Unburdensome.svelte
src/onboard/unconsentful/Voluntary.svelte

Just needed to export the `back` prop from all onboarding screen components, not just the one that uses `back`.

fix #37 back prop warning

---

README.md
changelog.md
src/onboard/Begin.svelte
src/onboard/Nav.svelte
src/onboard/consentful/Informed.svelte
src/onboard/consentful/Revertible.svelte
src/onboard/consentful/Specific.svelte
src/onboard/consentful/Unburdensome.svelte
src/onboard/consentful/Voluntary.svelte
src/onboard/unconsentful/Informed.svelte
src/onboard/unconsentful/Specific.svelte
src/onboard/unconsentful/Voluntary.svelte

fixes the input box bug in #52 -- here's the link, since there's other noise -- https://github.com/feltcoop/felt/pull/55/commits/c8de38a00b0e42523a7cbe1989a2827f9f745a5b -- this is definitely a "I should have stopped working to rest" bug
This also adds a space around every button's content. Whitespace behavior in HTML makes code formatting a bit quirky and hard to read if we don't do this, and it might ensure more consistent rendering.
Also makes the phone input focus when a provider is clicked.
Also fixes the links on `informed`. Clicking them otherwise breaks the experience, sends you back to the beginning.
Also fixes the changelog; 0.1.5 will never be published :butterfly:

fix #52 input box submission

---

src/app.css
src/lib/Checkbox.svelte
src/lib/Error_Message.svelte
src/lib/Help_Message.svelte
src/lib/Link_Path.svelte
src/lib/Message.svelte
src/lib/Nav.svelte
src/onboard/Begin.svelte
src/onboard/Onboard.svelte
src/onboard/unconsentful/Informed.svelte
src/onboard/unconsentful/Voluntary.svelte
src/routes/__layout.svelte
src/routes/sketch/index.svelte

Tightens up the CSS a lot - there was a lot of, and still is some, experimental styles and hacks to make things work.
Also misc simplifications and cleanup. It's deployed.

styles and cleanup

---

src/gro.config.ts
src/onboard/Begin.svelte

Updates the `Begin` screen content per our discussion.

update `Begin` content

---

src/app.css
src/lib/Checkbox.svelte
src/lib/Markup.svelte
src/lib/Tag.svelte
src/onboard/consentful/Specific.svelte
src/onboard/unconsentful/Specific.svelte

Adds a `<Tag>` component for usage in the `Specific` page.
Sorry for all the styles, new use cases meant more design system stuff.
When you're ready, go ahead and merge, I'm happy with it, and feel free to play around with it.

add tag component

---

src/lib/onboard/End.svelte
src/routes/__layout.svelte

This PR adds some fleshed out text to the end screen

Add a little more to conclusion page

---

src/lib/onboard/Credits.svelte

remove markup wrapper

---

src/lib/onboard/Credits.svelte

This adds a "made by" line that includes @feltcoop and other contributors.

add made by credits line

---

src/lib/consent/consent.ts
src/lib/onboard/Credits.svelte

Updates the credits line with the new content.

update research attribution line

---

changelog.md
package-lock.json
package.json
src/gro.config.ts

This is a quick hack to publish a working version for 0.2.

fix published types

---

changelog.md
package-lock.json
package.json
src/gro.config.ts

Publishes our first Svelte component, `ui/Pending_Animation.svelte`. Upgrades Gro with its new functionality to enable this. ([added here](https://github.com/feltcoop/gro/pull/239)) This component is the most clearly useful and stable one that I saw.

publish Pending_Animation.svelte

---

src/lib/sketch/library/Library.svelte
src/lib/ui/style.css

improves the library sketch in various ways, some fixes along with minor additions/changes

library updates
