feltcoop/felt

src/lib/WaitingAnimation.svelte
This adds the `WaitingAnimation.svelte` component that we wrote over a year ago for the mockup. Still looks sharp!
This line:
```css
color: var(--primary_color, #495499);
```
is aspirational: if any parent in the DOM specifies a `--primary_color` [CSS custom property](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties), it'll use that, and if there is no such property, it falls back to a hardcoded blue. 
Here's a Svelte repl: https://svelte.dev/repl/a737cc455c7046e6a6f6faaca3695e77?version=3.36.0
=> add waiting animation component

src/lib/PendingAnimation.svelte
This renames `WaitingAnimation.svelte` to `PendingAnimation.svelte` per our discussion in #6.
It also removes the line that adds a color, deferring completely to the parent.
Attached is a screenshot of the terminal workflow to prepare this PR. Note it uses `git mv` for better tool awareness (is this needed nowadays? I think sometimes things go awry if there are changes in a manually moved file):
(in case the aliases are confusing: `gs=git status`, `gd=git diff`, `gp=git push`, `gc=git commit` but I never remember)
=> rename WaitingAnimation to PendingAnimation and remove color style

package-lock.json, src/app.css, src/lib/Icons.svelte, src/routes/index.svelte
This PR was motivated by changing this line:
> import * as icons from '$lib/icons.ts';
to this:
> import * as icons from '$lib/icons';
It's a quirk of TypeScript that we never import modules using the suffix `.ts`. The compiler actually disallows it and throws an error. Vite/SvelteKit allow it, and make it work, but it's making Vscode error. Further, the actual correct syntax for ES modules is not currently supported by Vite/SvelteKit, but I can only imagine they will fix it:
> import * as icons from '$lib/icons.js';
Some other changes:
- add `list-style: none` to the global `app.css`. This is the first global style rule added. The idea is that `li` gets used commonly, but you only want bullet point styling in "normal markup". We'll create a component or class for normal markup, which …
=> fix import and improve icons list style

README.md, package-lock.json, package.json, svelte.config.cjs
This implements `@sveltejs/adapter-static` and removes `@sveltejs/adapter-node`.
We now need to run `npm start` to run the `build/` output from `npm run build`. The readme now reflects this.
`gro start` should work like `npm start`, but it currently fails because it doesn't know how to detect a SvelteKit project. I'm going to work on that in the next week or so.
=> implement static adapter

GOVERNANCE.md
This finishes the migration from [feltcoop/felt-mockup](/feltcoop/felt-mockup), using the same Temporary Benevolent Dictator (TBD) document.
=> Temporary Benevolent Dictator (TBD)

changelog.md, src/index.ts
This removes the `Nav` component as an export from the project. Currently the code breaks in non-SvelteKit projects because this component is using the SvelteKit import `$app/stores`. We may have to support a separate entrypoint for SvelteKit-enabled modules. e.g. `@feltcoop/felt/kit` or `@feltcoop/felt/svelte-kit` or something. (not now, later)
Removing the export makes sense too, because `Nav`, as written, is specific to this app. It's odd that it's side by side with other modules in `src/lib` - I'm not sure what structure we ultimately want here. Bigger discussion we'll punt for now. I'm not sure I like SvelteKit's `src/lib/` namespacing, at least not as a wrapper for all sub packages - I've enjoyed organizing things as `src/{domain}`. Right now I do like putting `Nav` in `src/lib/` …
=> remove nav as public export

package.json
This simplifies the `package.json` usage of the `"exports"` key given that we don't use the [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports). I'm also tentatively removing the `"module"` field, which is non-standard and not necessary for our tools. The `"type": "module"` field should be the only thing modern tools need, I think.
=> simplify package json

changelog.md, package-lock.json, package.json, src/index.ts
This removes the exported Svelte components from the published package entrypoint. We're going to need to figure out a few things specific to Svelte here, so for now let's keep it simple and export only TypeScript for now.
It also upgrades Gro to the latest.
=> remove remaining Svelte components from public API

src/onboard/unconsentful/Revertible.svelte
This swaps text on a button's mouseover as an experiment on the "revertible" page. Not sure what to think right now -- it's deployed to the live website. Might be a dead end or lead to a better idea.
=> example swapping text

src/onboard/consentful/Revertible.svelte
This makes the consentful revertible step slightly more frictionful & informative, by popping up a second dialog with final confirmation and additional information. Maybe overkill? It's deployed.
=> add second confirmation diaglog to consentful revertible

src/consent/Consent_Principle_View.svelte, src/consent/consent.ts
This changes the `description` property of `Consent_Principle` to `summary` to match ActivityStreams: https://ryanatkn.github.io/corpus-activity-streams/#summary
=> change description field name to summary

src/onboard/consentful/Unburdensome.svelte, src/routes/help.svelte
It's minimal, just un-breaks the experience.
Mirrors the `end` page content
addresses but doesn't necessarily close https://github.com/feltcoop/felt/issues/43
also adds a help page at felt.dev/help
=> add content for `consentful-unburdensome`

src/gro.config.ts, src/util/terminal.ts
We're re-exporting `kleur` here, and this maps the `bgColorname` exports to `bg_colorname`. 
Going forward I'm not 100% on this re-exporting pattern, but it's fine for now.
=> update terminal color api and add missing util to build

src/app.css, src/lib/Markup.svelte, src/lib/onboard/consentful/Specific.svelte, src/lib/onboard/unconsentful/Specific.svelte
Changes a few styles. The removed variables were no-ops, except they did change the size of the default checkbox content; if that was intentional we should change the default size in `app.css`.
=> styling tweaks

src/lib/onboard/consentful/Informed.svelte, src/lib/onboard/consentful/Revertible.svelte, src/lib/onboard/unconsentful/Informed.svelte, src/lib/onboard/unconsentful/Revertible.svelte
Adds content for #41 to the `revertible` screen. Also tweaks both sides of `informed` a bit.
=> revertible content

src/app.css, src/lib/onboard/Credits.svelte, src/lib/onboard/End.svelte, src/lib/onboard/Onboard.svelte, src/lib/onboard/consentful/Informed.svelte, src/lib/onboard/consentful/Unburdensome.svelte, src/lib/onboard/onboard.ts, src/lib/onboard/unconsentful/Specific.svelte
The main change here is that your current state (which of the 7 screens) is now saved to `localStorage`, and should persist on refresh. This makes the experience much better if you click away to another link or otherwise reload.
A second important change is adding a `devmode` toggle button and descriptive line at the end screen.
This also restructures some content and makes some minor changes, like making word case more consistent in various usage. 
It also fixes the selection highlight -- turns out text selection was not broken, but I had an obsolete CSS var coloring it, so it was invisible.
=> persist state and tweak some content

src/lib/consent/consent.ts, src/lib/onboard/Credits.svelte
This closes #38 with the descriptions of the consent principles from http://consentful.systems/ and adds proper attribution. I simplified the credits line slightly, removing some of the previous wording that distracts from the newer version.
We'll probably need to rework styling or layout a bit -- I'll keep this PR content-only.
=> fix #38: add credits and summaries of the consent principles

package-lock.json, package.json, src/lib/onboard/unconsentful/Unburdensome.svelte, src/lib/onboard/unconsentful/Voluntary.svelte, src/routes/__layout.svelte, svelte.config.js
This makes the changes described in #77 to make the social logins appear only after a failed attempt to login with a username and password.
It also fixes the favicon link, cleans some things up, and upgrades to the latest SvelteKit.
closes #77
=> fix #77: streamline `unconsentful:voluntary`

svelte.config.js
Removes the obsolete Vite config from `svelte.config.js`.
=> remove ssr config

package-lock.json, package.json, src/gro.config.ts
This upgrades Gro to 0.27, which reworks a lot of internals and has some breaking changes, including [the switch to `snake_case`](https://github.com/feltcoop/gro/pull/210).
=> upgrade gro

README.md, changelog.md, package-lock.json, package.json, src/gro.config.ts, src/index.ts, src/lib/Checkbox.svelte, src/lib/devmode.ts, src/lib/index.ts, src/lib/onboard/End.svelte, src/lib/onboard/Nav.svelte, src/lib/util/print.ts, src/lib/util/process.ts, src/lib/util/timings.test.ts, src/lib/util/timings.ts, src/routes/__layout.svelte
This updates to the latest version of Gro which is now `snake_case`.
When this PR is finished, we'll be able to finally complete this `felt-server` PR: https://github.com/feltcoop/felt-server/pull/42
=> fix publishing and update gro adapters and plugins

changelog.md, package-lock.json, package.json
Upgrades the patch version of Gro to 0.28.2 which uses the latest minor version of Felt. Shouldn't change anything, but ensures the mutual dependencies are playing well together.
=> upgrade gro patch version

changelog.md, package-lock.json, package.json, src/lib/index.ts, src/lib/util/async.ts
Exports `Async_Status` and `wait` from the root, so they're available when importing from `@feltcoop/felt` directly, instead of needing to specify the full path at `@feltcoop/felt/util/async.js`. These are heavily used -- I don't know what we want to export at the top level, so I'm starting slowly, and these are obvious choices.
Another option is having minimal top-level exports, possibly removing the rather meaningless `util/` namespacing.
Also updates to the latest version of Gro.
=> export async helpers from root

src/lib/sketch/onboard/consentful/Voluntary.svelte, src/lib/sketch/onboard/unconsentful/Voluntary.svelte
I started making the changes I proposed. This one is a simple fix of the wording on the Voluntary page, for both consentful and unconsentful versions: this is fake --> this is a fake sign-up / this is not real --> this is not a real sign-up
It'll take me some time to change the emoji (as I'm still getting used to the code :)), so I decided to make this pull request first. Please let me know if I need to follow any convention or rules!
=> Fixed wording of messages shown on the Voluntary page 

src/lib/sketch/onboard/consentful/Voluntary.svelte, src/lib/sketch/onboard/unconsentful/Voluntary.svelte, src/lib/ui/icons.ts, src/lib/ui/message.ts
Changed the emoji used in the voluntary consentful and unconsentful pages to ✨. Added a new status to Message called "inform" for this. Might end up changing the emoji to something else if people find it confusing.
In order to help us easily visualize & review components, please consider putting a [Svelte REPL](https://svelte.dev/repl) example below:
<REPL link goes here>
=> Changed the emoji used in the voluntary page
